use serde::{Deserialize, Serialize};

use crate::models::api::url_hints::UrlHints;

#[derive(Debug, Serialize, Deserialize)]
pub struct BandcampItem {
    pub fan_id: u64,
    pub item_id: u64,
    pub item_type: String,
    pub band_id: u64,
    pub added: String,
    pub updated: String,
    pub purchased: String,
    pub sale_item_id: u64,
    pub sale_item_type: String,
    pub tralbum_id: u64,
    pub tralbum_type: String,
    pub featured_track: Option<u64>,
    pub why: Option<String>,
    pub hidden: Option<bool>,
    pub index: Option<u32>,
    pub also_collected_count: u32,
    pub url_hints: UrlHints,
    pub item_title: String,
    pub item_url: String,
    pub item_art_id: u64,
    pub item_art_url: String,
    pub item_art: ItemArt,
    pub band_name: String,
    pub band_url: String,
    pub genre_id: Option<u32>,
    pub featured_track_title: Option<String>,
    pub featured_track_number: Option<u32>,
    pub featured_track_is_custom: bool,
    pub featured_track_duration: Option<f64>,
    pub featured_track_url: Option<String>,
    pub featured_track_encodings_id: Option<u64>,
    pub package_details: Option<String>,
    pub is_purchasable: bool,
    pub is_private: bool,
    pub is_preorder: bool,
    pub is_giftable: bool,
    pub is_subscriber_only: bool,
    pub is_subscription_item: bool,
    pub service_name: Option<String>,
    pub service_url_fragment: Option<String>,
    pub gift_sender_name: Option<String>,
    pub gift_sender_note: Option<String>,
    pub gift_id: Option<u64>,
    pub gift_recipient_name: Option<String>,
    pub album_id: Option<u64>,
    pub album_title: Option<String>,
    pub listen_in_app_url: String,
    pub band_location: Option<String>,
    pub band_image_id: Option<u64>,
    pub release_count: Option<u32>,
    pub message_count: Option<u32>,
    pub is_set_price: bool,
    pub price: f64,
    pub has_digital_download: Option<bool>,
    pub merch_ids: Option<Vec<u64>>,
    pub merch_sold_out: Option<bool>,
    pub currency: String,
    pub label: Option<String>,
    pub label_id: Option<u64>,
    pub require_email: Option<bool>,
    pub item_art_ids: Option<Vec<u64>>,
    pub releases: Option<Vec<String>>,
    pub discount: Option<f64>,
    pub token: String,
    pub variant_id: Option<u64>,
    pub merch_snapshot: Option<String>,
    pub featured_track_license_id: Option<u64>,
    pub licensed_item: Option<bool>,
    pub download_available: bool,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ItemArt {
    pub url: String,
    pub thumb_url: String,
    pub art_id: u64,
}
