use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::models::{api::url_hints::UrlHints, bandcamp_format::BandcampFormat};

#[derive(Debug, Serialize, Deserialize)]
pub struct BandcampSale {
    pub sale_id: u64,
    pub item_type: String,
    pub item_id: u64,
    pub sale_release_date: Option<String>,
    pub quantity: u32,
    pub unit_price: f64,
    pub currency: String,
    pub sold_date: String,
    pub download_type: String,
    pub download_id: u64,
    pub sale_item_state: String,
    pub band_id: u64,
    pub band_name: String,
    pub genre_id: Option<u32>,
    pub band_enabled: u32,
    pub has_enhanced_seller: u32,
    pub payment_id: u64,
    pub payment_type: String,
    pub buyer_type: String,
    pub buyer_id: Option<u64>,
    pub payment_email: String,
    pub fulfillment_days: Option<u32>,
    pub package_title: Option<String>,
    pub package_type_id: Option<u32>,
    pub options_title: Option<String>,
    pub is_live_ticket: Option<bool>,
    pub live_event_id: Option<u64>,
    pub live_event_title: Option<String>,
    pub live_event_description: Option<String>,
    pub live_event_scheduled_start_date: Option<String>,
    pub live_event_scheduled_end_date: Option<String>,
    pub live_event_end_date: Option<String>,
    pub live_event_timezone_sym_id: Option<u32>,
    pub service_type: Option<String>,
    pub shippable: Option<bool>,
    pub marked_shipped_date: Option<String>,
    pub license_id: Option<u32>,
    pub option_name: Option<String>,
    pub package_subdomain: String,
    pub package_custom_domain: Option<String>,
    pub package_custom_domain_verified: Option<bool>,
    pub package_slug_text: Option<String>,
    pub package_slug_type: Option<String>,
    pub art_id: u64,
    pub package_image_id: Option<u64>,
    pub release_date: Option<String>,
    pub package_release_date: Option<String>,
    pub tralbum_id: u64,
    pub download_pref: u32,
    pub killed: Option<bool>,
    pub gift_sender_note: Option<String>,
    pub gift_state: Option<String>,
    pub gift_redeemed_date: Option<String>,
    pub gift_recipient_email_hidden: Option<String>,
    pub gift_recipient_email: Option<String>,
    pub gift_sender_name: Option<String>,
    pub gift_recipient_name: Option<String>,
    pub gift_card_value: Option<f64>,
    pub gift_card_art_id: Option<u64>,
    pub gift_card_currency: Option<String>,
    pub gift_card_recipient_email: Option<String>,
    pub label_mailing_list_address: Option<String>,
    pub label_mailing_list_unsubscribe: Option<bool>,
    pub subscriber_only: Option<bool>,
    pub tax_system: Option<i64>,
    #[serde(rename = "type")]
    pub item_type_name: String,
    pub is_preorder: Option<bool>,
    pub package_type_name: Option<String>,
    pub includes_digital: bool,
    pub nodl_desc: Option<String>,
    pub desc: Option<String>,
    pub title: String,
    pub track_count: Option<u32>,
    pub desc_track_count: Option<u32>,
    pub artist: String,
    pub url_hints: UrlHints,
    pub page_url: String,
    pub gift_link: String,
    pub thumb_title: String,
    pub payment_amt: String,
    pub shareable: bool,
    pub downloads: HashMap<String, BandcampFormat>,
    pub ready: bool,
    pub notify_me: bool,
    pub notify_me_label: bool,
    pub min_price: f64,
    pub is_pure_free: bool,
    pub download_type_str: String,
    pub paid_for: bool,
    pub is_name_your_price: bool,
}

impl BandcampSale {
    pub fn get_format_by_encoding(&self, encoding: &str) -> Option<&BandcampFormat> {
        self.downloads.get(encoding)
    }
}
